package com.example.yudongzhou.daodemo.dao;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.util.Log;

import org.greenrobot.greendao.AbstractDaoMaster;
import org.greenrobot.greendao.database.StandardDatabase;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseOpenHelper;
import org.greenrobot.greendao.identityscope.IdentityScopeType;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/**
 * Master of DAO (schema version 4): knows all DAOs.
 */
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 4;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(Database db, boolean ifNotExists) {
        BodyFatWeighDataRecordDao.createTable(db, ifNotExists);
        BodyFatWeighDayDataDao.createTable(db, ifNotExists);
        BodyFatWeighMonthDataDao.createTable(db, ifNotExists);
        BodyFatWeighWeekDataDao.createTable(db, ifNotExists);
        BodyFatWeighYearDataDao.createTable(db, ifNotExists);
        HamnatodynamometerDataRecordDao.createTable(db, ifNotExists);
        SmartDeviceInfoDao.createTable(db, ifNotExists);
        SmartDeviceOwnerDao.createTable(db, ifNotExists);
        SportDataRecordDao.createTable(db, ifNotExists);
        SportDayDataDao.createTable(db, ifNotExists);
        SportMonthDataDao.createTable(db, ifNotExists);
        SportWeekDataDao.createTable(db, ifNotExists);
        SportYearDataDao.createTable(db, ifNotExists);
        SonDao.createTable(db, ifNotExists);
        BaseBeanDao.createTable(db, ifNotExists);
    }

    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(Database db, boolean ifExists) {
        BodyFatWeighDataRecordDao.dropTable(db, ifExists);
        BodyFatWeighDayDataDao.dropTable(db, ifExists);
        BodyFatWeighMonthDataDao.dropTable(db, ifExists);
        BodyFatWeighWeekDataDao.dropTable(db, ifExists);
        BodyFatWeighYearDataDao.dropTable(db, ifExists);
        HamnatodynamometerDataRecordDao.dropTable(db, ifExists);
        SmartDeviceInfoDao.dropTable(db, ifExists);
        SmartDeviceOwnerDao.dropTable(db, ifExists);
        SportDataRecordDao.dropTable(db, ifExists);
        SportDayDataDao.dropTable(db, ifExists);
        SportMonthDataDao.dropTable(db, ifExists);
        SportWeekDataDao.dropTable(db, ifExists);
        SportYearDataDao.dropTable(db, ifExists);
        SonDao.dropTable(db, ifExists);
        BaseBeanDao.dropTable(db, ifExists);
    }

    /**
     * WARNING: Drops all table on Upgrade! Use only during development.
     * Convenience method using a {@link DevOpenHelper}.
     */
    public static DaoSession newDevSession(Context context, String name) {
        Database db = new DevOpenHelper(context, name).getWritableDb();
        DaoMaster daoMaster = new DaoMaster(db);
        return daoMaster.newSession();
    }

    public DaoMaster(SQLiteDatabase db) {
        this(new StandardDatabase(db));
    }

    public DaoMaster(Database db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(BodyFatWeighDataRecordDao.class);
        registerDaoClass(BodyFatWeighDayDataDao.class);
        registerDaoClass(BodyFatWeighMonthDataDao.class);
        registerDaoClass(BodyFatWeighWeekDataDao.class);
        registerDaoClass(BodyFatWeighYearDataDao.class);
        registerDaoClass(HamnatodynamometerDataRecordDao.class);
        registerDaoClass(SmartDeviceInfoDao.class);
        registerDaoClass(SmartDeviceOwnerDao.class);
        registerDaoClass(SportDataRecordDao.class);
        registerDaoClass(SportDayDataDao.class);
        registerDaoClass(SportMonthDataDao.class);
        registerDaoClass(SportWeekDataDao.class);
        registerDaoClass(SportYearDataDao.class);
        registerDaoClass(SonDao.class);
        registerDaoClass(BaseBeanDao.class);
    }

    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }

    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }

    /**
     * Calls {@link #createAllTables(Database, boolean)} in {@link #onCreate(Database)} -
     */
    public static abstract class OpenHelper extends DatabaseOpenHelper {
        public OpenHelper(Context context, String name) {
            super(context, name, SCHEMA_VERSION);
        }

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(Database db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }

    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name) {
            super(context, name);
        }

        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(Database db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

}
